import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useNavigate, useParams } from "react-router-dom";
import { marked } from "marked";
import {
    AlertTriangle,
    BookOpen01,
    InfoCircle,
    Lightbulb02,
    Menu02,
    SearchLg,
    XClose,
} from "@untitledui/icons";

import { Input } from "@/components/base/input/input";
import { cx } from "@/utils/cx";

/**
 * End-user documentation (ADR-011, ADR-014).
 *
 * Three columns: the page list on the left, the content in the middle, and a
 * table of contents on the right that follows the reader down the page. Its own
 * controls — the page-list toggle and the search field — are portalled into the
 * panel's header rather than rendered as a second bar beneath it.
 *
 * The styling in `styles/documentation.css` is built on this panel's design
 * tokens, so the section reads as part of the admin and follows a rebrand.
 *
 * The markdown under `src/docs/pages/` is generated by `npm run docs` and is
 * imported at build time: no endpoint, no collection, no runtime fetch. Vite's
 * `import.meta.glob` with `query: "?raw"` inlines every page into the bundle,
 * so the section works offline and cannot drift from the build it shipped in.
 */
const PAGE_SOURCES = import.meta.glob("../docs/pages/*.md", { query: "?raw", import: "default", eager: true });
const SCREENSHOTS = import.meta.glob("../docs/screenshots/*.png", { query: "?url", import: "default", eager: true });

/** "../docs/pages/department.md" -> "department" */
const keyOf = (filePath) => filePath.split("/").pop().replace(/\.md$/, "");

const PAGES = Object.fromEntries(
    Object.entries(PAGE_SOURCES).map(([filePath, source]) => [keyOf(filePath), source]),
);

/** Basename -> bundled URL, for rewriting the generator's relative paths. */
const IMAGE_URLS = Object.fromEntries(
    Object.entries(SCREENSHOTS).map(([filePath, url]) => [filePath.split("/").pop(), url]),
);

/** Heading text -> the id an anchor and the table of contents both use. */
export const slugify = (text) =>
    text
        .toLowerCase()
        .replace(/[^\w\s-]/g, "")
        .trim()
        .replace(/\s+/g, "-");

/**
 * The page list, read from the generated index.
 *
 * Parsing the index rather than keeping a second list here means ordering and
 * grouping have one home — the generator — so adding a screen to the manifest
 * is enough to make it appear in the navigation.
 */
export const parseIndex = (source) => {
    if (!source) return [];
    const groups = [];
    for (const line of source.split("\n")) {
        const heading = line.match(/^##\s+(.*)$/);
        if (heading) {
            groups.push({ title: heading[1].trim(), items: [] });
            continue;
        }
        const item = line.match(/^-\s+\[(.+?)\]\((.+?)\)\s*$/);
        if (item && groups.length) groups.at(-1).items.push({ title: item[1], key: item[2] });
    }
    return groups;
};

/** The `## ` headings of a page, in order, for the table of contents. */
export const parseHeadings = (source) => {
    if (!source) return [];
    return source
        .split("\n")
        .map((line) => line.match(/^##\s+(.+)$/))
        .filter(Boolean)
        .map((match) => ({ title: match[1].trim(), id: slugify(match[1].trim()) }));
};

const CALLOUTS = {
    NOTE: { icon: InfoCircle, className: "doc-callout-note", label: "Note" },
    INFO: { icon: InfoCircle, className: "doc-callout-note", label: "Info" },
    TIP: { icon: Lightbulb02, className: "doc-callout-tip", label: "Tip" },
    WARNING: { icon: AlertTriangle, className: "doc-callout-warning", label: "Warning" },
};

/**
 * A renderer that turns the generated markdown into Material-shaped HTML.
 *
 * Three transformations beyond ordinary markdown:
 *
 * - `## ` headings gain an id, so the table of contents can link to them and
 *   the scroll spy can find them.
 * - `> [!WARNING] Title` blockquotes become coloured callouts.
 * - The generator's relative `../screenshots/x.png` paths are rewritten onto
 *   the URLs Vite produced for the bundled images.
 */
const buildRenderer = () => {
    const renderer = new marked.Renderer();

    renderer.heading = function heading({ tokens, depth }) {
        const text = this.parser.parseInline(tokens);
        const plain = text.replace(/<[^>]*>/g, "");
        const id = slugify(plain);
        // Only h2s are linkable — they are what the table of contents lists.
        if (depth !== 2) return `<h${depth}>${text}</h${depth}>`;
        return `<h2 id="${id}" class="doc-heading">${text}<a class="doc-anchor" href="#${id}" aria-label="Link to this section">#</a></h2>`;
    };

    renderer.blockquote = function blockquote({ tokens }) {
        const inner = this.parser.parse(tokens);
        const match = inner.match(/\[!(\w+)\]\s*([^<\n]*)/);
        if (!match) return `<blockquote>${inner}</blockquote>`;

        const kind = CALLOUTS[match[1].toUpperCase()] ?? CALLOUTS.NOTE;
        const title = match[2].trim() || kind.label;
        const body = inner.replace(/\[!\w+\]\s*[^<\n]*/, "");
        return (
            `<div class="doc-callout ${kind.className}" data-icon="${match[1].toUpperCase()}">` +
            `<p class="doc-callout-title">${title}</p>` +
            `<div class="doc-callout-body">${body}</div>` +
            `</div>`
        );
    };

    /*
     * The generator emits both themes' screenshots and marks each with its theme
     * in the title slot; only the one matching the active theme is shown, by a
     * rule in `documentation.css`. Doing it in CSS rather than here means a
     * theme toggle swaps every picture without re-rendering the markdown.
     */
    renderer.image = function image({ href, title, text }) {
        const file = href.split("/").pop();
        const resolved = IMAGE_URLS[file] ?? href;
        const theme = title === "dark" || title === "light" ? title : null;
        const themed = theme ? ` data-theme="${theme}"` : "";
        return `<img src="${resolved}" alt="${text}"${themed} loading="lazy" />`;
    };

    return renderer;
};

const RENDERER = buildRenderer();

const Documentation = () => {
    const { pageKey } = useParams();
    const navigate = useNavigate();
    const [query, setQuery] = useState("");
    const [activeHeading, setActiveHeading] = useState(null);
    const [navOpen, setNavOpen] = useState(false);
    const articleRef = useRef(null);
    // The layout's header slot is a real DOM node, so it is only there after the
    // first paint; state rather than a ref, to re-render once it appears.
    const [headerSlot, setHeaderSlot] = useState(null);

    const groups = useMemo(() => parseIndex(PAGES.index), []);
    const current = pageKey && PAGES[pageKey] ? pageKey : "index";
    const source = PAGES[current];

    const html = useMemo(
        () => (source ? marked.parse(source, { renderer: RENDERER, async: false }) : ""),
        [source],
    );
    const headings = useMemo(() => parseHeadings(source), [source]);

    useEffect(() => {
        setHeaderSlot(document.getElementById("app-header-slot"));
    }, []);

    // A deep link to a page that no longer exists should not leave the address
    // bar claiming something that is not on screen.
    useEffect(() => {
        if (pageKey && !PAGES[pageKey]) navigate("/documentation", { replace: true });
    }, [pageKey, navigate]);

    // Moving between pages should start at the top, not wherever the last page
    // was scrolled to.
    useEffect(() => {
        window.scrollTo({ top: 0 });
        setActiveHeading(headings[0]?.id ?? null);
        setNavOpen(false);
    }, [current]);

    /**
     * Highlights the section being read.
     *
     * `rootMargin` pulls the trigger line down from the very top so a heading
     * counts as current once it is comfortably in view, which is what makes the
     * highlight track reading rather than lag a screen behind.
     */
    useEffect(() => {
        if (!articleRef.current || !headings.length) return undefined;
        const targets = headings
            .map((heading) => document.getElementById(heading.id))
            .filter(Boolean);

        const observer = new IntersectionObserver(
            (entries) => {
                const visible = entries
                    .filter((entry) => entry.isIntersecting)
                    .sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
                if (visible.length) setActiveHeading(visible[0].target.id);
            },
            { rootMargin: "-80px 0px -70% 0px", threshold: 0 },
        );
        for (const target of targets) observer.observe(target);
        return () => observer.disconnect();
    }, [headings, html]);

    const filtered = useMemo(() => {
        const needle = query.trim().toLowerCase();
        if (!needle) return groups;
        return groups
            .map((group) => ({
                ...group,
                items: group.items.filter(
                    (item) =>
                        item.title.toLowerCase().includes(needle) ||
                        (PAGES[item.key] ?? "").toLowerCase().includes(needle),
                ),
            }))
            .filter((group) => group.items.length);
    }, [groups, query]);

    const navigation = (
        <nav aria-label="Documentation pages">
            <div className="doc-nav-group">
                <button
                    type="button"
                    onClick={() => navigate("/documentation")}
                    className={cx("doc-nav-link", current === "index" && "doc-nav-link-active")}
                >
                    Overview
                </button>
            </div>
            {filtered.map((group) => (
                <div key={group.title} className="doc-nav-group">
                    <span className="doc-nav-label">{group.title}</span>
                    {group.items.map((item) => (
                        <button
                            key={item.key}
                            type="button"
                            onClick={() => navigate(`/documentation/${item.key}`)}
                            className={cx("doc-nav-link", current === item.key && "doc-nav-link-active")}
                        >
                            {item.title}
                        </button>
                    ))}
                </div>
            ))}
            {!filtered.length && <p className="doc-nav-link">No pages match that search.</p>}
        </nav>
    );

    /*
     * The page-list toggle and the documentation search go into the panel's own
     * header rather than into a masthead of this section's own. Rendering a
     * second full-width bar directly beneath a 4rem header read as two stacked
     * headers and cost most of a screen of vertical space before any
     * documentation appeared.
     *
     * A portal rather than a prop or a context: the layout owns the header, this
     * screen owns these controls, and nothing else in the app needs to know that
     * either is true. The slot is empty on every other screen.
     */
    const headerControls = headerSlot
        ? createPortal(
              <>
                  <button
                      type="button"
                      className="doc-nav-toggle"
                      onClick={() => setNavOpen((open) => !open)}
                      aria-label={navOpen ? "Close page list" : "Open page list"}
                  >
                      {navOpen ? <XClose className="size-5" /> : <Menu02 className="size-5" />}
                  </button>
                  <BookOpen01 className="hidden size-5 shrink-0 text-fg-secondary sm:block" />
                  <p className="truncate text-sm font-semibold text-primary">Documentation</p>

                  <div className="doc-search ml-auto w-40 shrink-0 sm:w-64">
                      <Input
                          icon={SearchLg}
                          placeholder="Search"
                          value={query}
                          onChange={setQuery}
                          aria-label="Search documentation"
                      />
                  </div>
              </>,
              headerSlot,
          )
        : null;

    return (
        <div className="doc-shell">
            {headerControls}

            <div className="doc-body">
                <aside className={cx("doc-sidebar", navOpen && "doc-sidebar-open")}>{navigation}</aside>

                <main className="doc-main">
                    {/* The markdown is generated from files in this repository and
                        committed — never user input — so there is nothing to
                        sanitise here. */}
                    <article
                        ref={articleRef}
                        className="doc-article"
                        dangerouslySetInnerHTML={{ __html: html }}
                    />
                </main>

                {headings.length > 1 && (
                    <aside className="doc-toc" aria-label="On this page">
                        <p className="doc-toc-title">On this page</p>
                        <ul>
                            {headings.map((heading) => (
                                <li key={heading.id}>
                                    <a
                                        href={`#${heading.id}`}
                                        className={cx(
                                            "doc-toc-link",
                                            activeHeading === heading.id && "doc-toc-link-active",
                                        )}
                                    >
                                        {heading.title}
                                    </a>
                                </li>
                            ))}
                        </ul>
                    </aside>
                )}
            </div>
        </div>
    );
};

export default Documentation;
