import { Navigate } from "react-router-dom";
import { crudRoutes } from "@/components/crud";
import { UNIFORM_ENTITIES } from "@/entities";
import { ADVANCED_ENTITIES, seoPageConfig } from "@/entities/advanced";

import Login from "../pages/Authentication/Login";
import UserProfile from "../pages/Authentication/user-profile";
import Dashboard from "../pages/Dashboard/Dashboard";
import UserRoles from "../pages/Setup/UserRoles";
import DashboardBuilder from "../pages/Setup/DashboardBuilder";
import DashboardSectionEditor from "../pages/Setup/DashboardSectionEditor";
import LoginAttemptLogs from "../pages/Master/LoginAttemptLogs";
import AuditLog from "../pages/Master/AuditLog";
import SeoPageEditor from "../pages/Setup/SeoPageEditor";
import SeoSettings from "../pages/Setup/SeoSettings";
import SeoNotFoundLog from "../pages/Setup/SeoNotFoundLog";
import Documentation from "../pages/Documentation";
import Watchlist from "../pages/StockTracker/Watchlist";

const authProtectedRoutes = [
    { path: "/dashboard", component: <Dashboard /> },
    { path: "/profile", component: <UserProfile /> },

    // Bullish Tracker (system-design: not CRUD — an import + matching
    // workflow, decision-tree step 4).
    { path: "/watchlist", component: <Watchlist /> },

    // list / add / view / edit for every CRUD entity
    ...[...UNIFORM_ENTITIES, ...ADVANCED_ENTITIES].flatMap(crudRoutes),

    // SEO pages keep the generated list, view and delete, but the two form
    // routes are replaced: that screen's value is the live search/social
    // preview beside the inputs, which an entity config cannot express.
    crudRoutes(seoPageConfig)[0],
    { path: "/seo-pages/add", component: <SeoPageEditor key="seo-page-add" mode="add" /> },
    { path: "/seo-pages/:id", component: <SeoPageEditor key="seo-page-view" mode="view" /> },
    { path: "/seo-pages/:id/edit", component: <SeoPageEditor key="seo-page-edit" mode="edit" /> },

    // Not CRUD screens: a permission matrix, a read-only audit log, a settings
    // singleton and a 404 log whose point is turning entries into redirects.
    { path: "/user-roles", component: <UserRoles /> },
    // Dashboard Builder is the library + the dashboard assignment; building one
    // section is its own screen for the same reason as SeoPageEditor — the
    // live preview beside the inputs needs the room.
    { path: "/dashboard-builder", component: <DashboardBuilder /> },
    { path: "/dashboard-builder/add", component: <DashboardSectionEditor key="dashboard-section-add" mode="add" /> },
    { path: "/dashboard-builder/edit/:id", component: <DashboardSectionEditor key="dashboard-section-edit" mode="edit" /> },
    { path: "/login-attempt-logs", component: <LoginAttemptLogs /> },
    { path: "/audit-log", component: <AuditLog /> },
    { path: "/seo-settings", component: <SeoSettings /> },
    { path: "/seo-404", component: <SeoNotFoundLog /> },

    // End-user documentation (ADR-011). The markdown is generated by
    // `npm run docs` and bundled at build time, so these are plain routes with
    // no data loading of their own.
    { path: "/documentation", component: <Documentation /> },
    { path: "/documentation/:pageKey", component: <Documentation /> },

    // Dashboard is hidden from the sidebar (user request, 2026-09-29) —
    // Watchlist is the real home now.
    { path: "/", exact: true, component: <Navigate to="/watchlist" /> },
    { path: "*", component: <Navigate to="/watchlist" /> },
];

const publicRoutes = [{ path: "/", component: <Login /> }];

export { authProtectedRoutes, publicRoutes };
